### ISSUE TITLE
Hard crash with Glyphs 3.0.5

### ISSUE THREAD

**Issue by colinmford** [schriftgestalt/DrawBotGlyphsPlugin#11]
Hi @schriftgestalt,

I recently upgraded to Glyphs 3.0.5 (3129). I am on mac OS 10.15.

If I run this plugin from the File menu (File > New Drawbot) or even just type `import drawBot` in the Macro panel, Glyphs hard crashes without an error. 

I imagine this is because this plugin hasn't gotten an update in a while — any chance it could use a more modern version of DrawBot?

Crash report attached, if it's helpful [crash report.txt](https://github.com/schriftgestalt/DrawBotGlyphsPlugin/files/8781581/crash.report.txt)

**Comment by schriftgestalt** [comment]
I just tried it and it works for me. What version of python and pyobjc do you have?

**Comment by colinmford** [comment]
I'm using the Glyphs Python Plugin, Version 3.9.1. PyObjC version is 7.1

```python
import sys
import objc
print(sys.version)
print(objc.__version__)

> 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:44:01) 
[Clang 12.0.0 (clang-1200.0.32.27)] 
> 7.1
```

**Comment by colinmford** [comment]
And thank you so much for your quick response! I really appreciate this!

**Comment by schriftgestalt** [comment]
I have the same versions. Can you remove all other plugins?

**Comment by colinmford** [comment]
@schriftgestalt: 

I did a fresh install on a newer machine and it does work — must be the older operating system. Thanks for your help, I'll close.

This pop-up did come up on the first run of the newly-installed DrawBot plugin, though, so perhaps this plugin does need an update anyway?

<img width="435" alt="image" src="https://user-images.githubusercontent.com/671409/170737876-2bde1b1e-d920-47d7-a03e-1d5585d30d3b.png">
