### ISSUE TITLE
Bug : Export .gif format

### ISSUE THREAD

**Issue by HugoJourdan** [schriftgestalt/DrawBotGlyphsPlugin#12]
It's seem that exporting .gif with more than one frame is bugged

```python
for i in range(10):
    newPage(50,50)
saveImage("~/Desktop/firstImage.gif")
```

**Comment by jenskutilek** [comment]
Do you get a traceback? Can't reproduce any error on my machine.

**Comment by HugoJourdan** [comment]
My bad, the issue seems to be due to a conflict with another DrawBot installation in a different plugin.
