### ISSUE TITLE
Update to new API

### ISSUE THREAD

**Issue by Mark2Mark** [schriftgestalt/DrawBotGlyphsPlugin#2]
I think this one needs some minor changes, too, in order to work with Glyphs build 1103+

I see many `import AppKit`and opening DrawBot crashes Glyphs with a Traceback
`*** Terminating app due to uncaught exception 'OC_PythonException', reason: '<type 'exceptions.ImportError'>: cannot import name PY2'`

**Comment by schriftgestalt** [comment]
You need to update to the latest version of drawbot, vanilla and fontTools

**Comment by Mark2Mark** [comment]
I thought DrawBot will be up to date anyway, since it is installed via the Plugin Manager. Anyway: I forgot about the others, installed and can confirm: it works.

Thank you!

BTW: The `import AppKit` statements are still in a lot of places of DrawBot. For instance in the `baseContext.py`. I thought you where planning on removing these for too heavy loading.
```
import AppKit
import CoreText
import Quartz
```

**Comment by schriftgestalt** [comment]
`import AppKit` is OK, only `from AppKit import *` is not.

**Comment by Mark2Mark** [comment]
Thanks for the Info 👍
