### ISSUE TITLE
from drawBot import * fails

### ISSUE THREAD

**Issue by peternowell** [schriftgestalt/DrawBotGlyphsPlugin#6]
I just got Glyphs 3 and installed the DrawBot plugin for it. Surprisingly, `from drawBot import *` fails because it can't find the `CoreText` module.

`ModuleNotFoundError: No module named 'CoreText'`

**Comment by schriftgestalt** [comment]
That is actually a problem with the installed python version. The Glyphs python plugin is already updated but the new version requires the cutting edge version. You can activate it in preferences > updates.
